export {default as Card} from './Card/Card'
// export {default as CardContainer} from './CardContainer/CardContainer'
export {default as Container} from './Container/Container'
export {default as Ride} from './Ride/Ride'
// export {default as Footer} from './Footer/Footer'
// export {default as Footer1} from './Footer1/Footer1'
// export {default as Navbar} from './Navbar/Navbar'
// export {default as Searchbar} from './Searchbar/Searchbar'
// export {default as Search} from './Search/Search'
// export {default as InputSelect} from './InputSelect/InputSelect'